=== BackupTheBerlios/lapucapu/lapucapu/klient/xml_szablony/message.dtd
<!ELEMENT xml (message,from,to,body)>
<!ELEMENT message EMPTY>
<!ELEMENT from (user)>
<!ELEMENT to (user+)>
<!ELEMENT body ANY>
<!ELEMENT user EMPTY>

<!ATTLIST message type CDATA #FIXED "message">
<!ATTLIST user uid CDATA #REQUIRED>

=== BackupTheBerlios/lapucapu/lapucapu/xml_szablony/message.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml SYSTEM "message.dtd">

<xml>
	<message type="request" value="message"/>
	<from>
		<user uid="0000001"/>
	</from>
	<to>
		<user uid="0000002"/>
		<user uid="0000003"/>
	</to>
	<body>Treść wiadomości , z fajnym formatowaniem ktorego jeszcze nie ma :)</body>
</xml>
