=== BackupTheBerlios/lapucapu/lapucapu/klient/xml_szablony/respose_users_list.dtd
<!ELEMENT xml (message,users)>
<!ELEMENT message EMPTY>
<!ELEMENT users (user*)>
<!ELEMENT user ANY>
<!ELEMENT nick (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ATTLIST message value CDATA #FIXED "users_list">
<!ATTLIST user uid CDATA #REQUIRED>

=== BackupTheBerlios/lapucapu/lapucapu/klient/xml_szablony/respose_users_list.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml SYSTEM "respose_users_list.dtd">
<xml>
	<message value="users_list"/>
	
	<users>
		<user uid="0000002">
			<nick>power</nick>
			<name>Mariusz</name>
			<surname>Walczyk</surname>
			<!-- dodajcie jakie tam jeszcze info chcecie -->
		</user>
		
		<user uid="0000003">
			<nick>praf</nick>
			<name>Rafał</name>
			<surname>Piotrowski</surname>
		</user>
		
		<user uid="0000004">
			<nick>endriu</nick>
			<name>Andrzej</name>
			<surname>Wańkowicz</surname>
		</user>
		
		<user uid="0000005">
			<nick>olo</nick>
			<name>Aleksander</name>
			<surname>Handzel</surname>
		</user>
	</users>
</xml>
