=== BackupTheBerlios/lapucapu/lapucapu/klient/xml_szablony/respose_users_states.dtd
<!ELEMENT xml (message,users)>
<!ELEMENT message EMPTY>
<!ELEMENT users (user*)>
<!ELEMENT user (status)>
<!ELEMENT status (#PCDATA)>
<!ATTLIST message type CDATA #FIXED "respose_users_states">
<!ATTLIST user uid CDATA #REQUIRED>
<!ATTLIST status state (online|offline|invisible|brb) #REQUIRED>

=== BackupTheBerlios/lapucapu/lapucapu/klient/xml_szablony/respose_users_states.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml SYSTEM "respose_users_states.dtd">
<!-- szablon odpowiedzi na rzadanie pokazania dostepnosci kontaktow -->

<xml>
	
	<message type="respose_users_states"/>

	<users>
		<user uid="0000002">
			<status state="online">Ciagle pisze w c++ :P</status>
		</user>
		
		<user uid="0000003">
			<status state="offline">Naprawde nie ma mnie</status>
		</user>
		
		<user uid="0000004">
			<status state="invisible">Ja was widze a wy mnie nie :P</status>
		</user>
		
		<user uid="0000005">
			<status state="brb">be right back</status>
		</user>
	</users>
</xml>
